# Используем базовый образ Python
FROM python:3

# Устанавливаем рабочую директорию внутри контейнера
WORKDIR /app

# Копируем файлы из текущего каталога в контейнер
COPY . /app

# Активируем виртуальную среду и устанавливаем в нее зависимости
RUN . ./env/bin/activate.fish && \
    pip install -r requirements.txt

# Запускаем скрипт main.py при запуске контейнера
CMD ["python", "main.py"]

